In [5]:
#- Imports e configurações
import warnings
import pandas as pd

warnings.filterwarnings("ignore")

In [6]:
df = pd.read_csv("train.csv")
df.head()

,id,Time,V1,V2,V3,V4,V5,V6,V7,V8,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,265519,161919.0,1.946747,-0.752526,-1.355130,-0.661630,1.502822,4.024933,-1.479661,1.139880,...,0.076197,0.297537,0.307915,0.690980,-0.350316,-0.388907,0.077641,-0.032248,7.32,0
1,180306,124477.0,2.035149,-0.048880,-3.058693,0.247945,2.943487,3.298697,-0.002192,0.674782,...,0.038628,0.228197,0.035542,0.707090,0.512885,-0.471198,0.002520,-0.069002,2.99,0
2,42665,41191.0,-0.991920,0.603193,0.711976,-0.992425,-0.825838,1.956261,-2.212603,-5.037523,...,-2.798352,0.109526,-0.436530,-0.932803,0.826684,0.913773,0.038049,0.185340,175.10,0
3,198724,132624.0,2.285718,-1.500239,-0.747565,-1.668119,-1.394143,-0.350339,-1.427984,0.010010,...,-0.139670,0.077013,0.208310,-0.538236,-0.278032,-0.162068,0.018045,-0.063005,6.10,0
4,82326,59359.0,-0.448747,-1.011440,0.115903,-3.454854,0.715771,-0.147490,0.504347,-0.113817,...,-0.243245,-0.173298,-0.006692,-1.362383,-0.292234,-0.144622,-0.032580,-0.064194,86.10,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227845 entries, 0 to 227844
Data columns (total 32 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   id      227845 non-null  int64
 1   Time    227845 non-null  float64
 2   V1      227845 non-null  float64
 3   V2      227845 non-null  float64
 4   V3      227845 non-null  float64
 5   V4      227845 non-null  float64
 6   V5      227845 non-null  float64
 7   V6      227845 non-null  float64
 8   V7      227845 non-null  float64
 9   V8      227845 non-null  float64
 10  V9      227845 non-null  float64
 11  V10     227845 non-null  float64
 12  V11     227845 non-null  float64
 13  V12     227845 non-null  float64
 14  V13     227845 non-null  float64
 15  V14     227845 non-null  float64
 16  V15     227845 non-null  float64
 17  V16     227845 non-null  float64
 18  V17     227845 non-null  float64
 19  V18     227845 non-null  float64
 20  V19     227845 non-null  float64
 21  V20     227845 non-null  float64
 22  V21     227845 non-null  float64
 23  V22     227845 non-null  float64
 24  V23     227845 non-null  float64
 25  V24     227845 non-null  float64
 26  V25     227845 non-null  float64
 27  V26     227845 non-null  float64
 28  V27     227845 non-null  float64
 29  V28     227845 non-null  float64
 30  Amount  227845 non-null  float64
 31  Class   227845 non-null  int64
dtypes: float64(30), int64(2)
memory usage: 55.6 MB

#Análise de valores faltantes

In [8]:
# 1. Contagem de missing values
print("\n1️⃣ MISSING VALUES POR COLUNA:")
missing_data = pd.DataFrame({
    'Coluna': df.columns,
    'Missing_Count': df.isnull().sum(),
    'Missing_Percent': (df.isnull().sum() / len(df)) * 100
})
missing_data = missing_data[missing_data['Missing_Count'] > 0].sort_values('Missing_Percent', ascending=False)
print(missing_data)

1️⃣ MISSING VALUES POR COLUNA:
Empty DataFrame
Columns: [Coluna, Missing_Count, Missing_Percent]
Index: []

Assim é possível perceber que esse dataframe não possui valores faltantes, logo não é necessário fazer nenhum tratamento para esse tipo

#Análise de duplicatas

In [9]:
print("\n6️⃣ VALORES ÚNICOS POR COLUNA:")
for col in df.columns:
    unique_count = df[col].nunique()
    print(f"{col}: {unique_count} valores únicos")

6️⃣ VALORES ÚNICOS POR COLUNA:
id: 227845 valores únicos
Time: 113920 valores únicos
V1: 221411 valores únicos
V2: 221411 valores únicos
V3: 221411 valores únicos
V4: 221411 valores únicos
V5: 221411 valores únicos
V6: 221411 valores únicos
V7: 221411 valores únicos
V8: 221411 valores únicos
V9: 221411 valores únicos
V10: 221411 valores únicos
V11: 221411 valores únicos
V12: 221411 valores únicos
V13: 221411 valores únicos
V14: 221411 valores únicos
V15: 221411 valores únicos
V16: 221411 valores únicos
V17: 221411 valores únicos
V18: 221411 valores únicos
V19: 221411 valores únicos
V20: 221411 valores únicos
V21: 221411 valores únicos
V22: 221411 valores únicos
V23: 221411 valores únicos
V24: 221411 valores únicos
V25: 221411 valores únicos
V26: 221411 valores únicos
V27: 221411 valores únicos
V28: 221411 valores únicos
Amount: 29367 valores únicos
Class: 2 valores únicos

Ao analisar os valores únicos percebe-se que id só possui valores únicos que servem como identificação das transações, logo não é importante para o modelo, o que nos permite dropar essa feature

In [10]:
df.drop(columns=['id'], inplace=True)

Como todas as features do tipo V apresentaram a mesma quantidade de valores únicos e eles não são a mesma quantidade de observações. Isso pode ser algo importante para ser análisado na Análise Exploratória de Dados

In [11]:
df_duplicates = df[df.duplicated(keep=False)]
df_duplicates.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
320,141741.0,1.926056,-0.119873,-0.293731,1.570672,-0.346180,-0.240244,-0.215856,-0.031748,1.116621,...,-0.516829,-1.163595,0.429179,-0.156733,-0.310978,-1.099442,0.060238,-0.030115,9.99,0
333,80555.0,-5.014467,3.854615,-2.016684,-0.031160,-2.757385,-0.414333,-2.548677,3.837625,-0.140853,...,0.001260,-0.412211,0.286055,-0.003974,0.368550,0.302515,0.070903,0.051772,2.15,0
393,149337.0,-1.538874,1.938769,-1.289902,-0.748175,-0.274495,-0.893620,-0.075625,1.210816,0.036569,...,-0.144143,-0.492212,0.169410,-0.675995,-0.629294,0.216508,0.223816,0.195294,2.22,0
818,33619.0,1.163253,-0.014139,1.272299,1.420947,-0.926893,-0.121972,-0.519157,0.093523,0.977292,...,-0.180902,-0.219039,0.020564,0.398989,0.448507,-0.456745,0.075666,0.035279,1.00,0
1633,80555.0,-4.998492,3.879776,-2.027856,-0.037342,-2.814195,-0.375703,-2.495673,3.826899,-0.143990,...,-0.006257,-0.407636,0.290606,-0.003164,0.370590,0.304171,0.085542,0.045585,14.90,0

In [12]:
df_duplicates.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1268 entries, 320 to 227696
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    1268 non-null   float64
 1   V1      1268 non-null   float64
 2   V2      1268 non-null   float64
 3   V3      1268 non-null   float64
 4   V4      1268 non-null   float64
 5   V5      1268 non-null   float64
 6   V6      1268 non-null   float64
 7   V7      1268 non-null   float64
 8   V8      1268 non-null   float64
 9   V9      1268 non-null   float64
 10  V10     1268 non-null   float64
 11  V11     1268 non-null   float64
 12  V12     1268 non-null   float64
 13  V13     1268 non-null   float64
 14  V14     1268 non-null   float64
 15  V15     1268 non-null   float64
 16  V16     1268 non-null   float64
 17  V17     1268 non-null   float64
 18  V18     1268 non-null   float64
 19  V19     1268 non-null   float64
 20  V20     1268 non-null   float64
 21  V21     1268 non-null   float64
 22  V22     1268 non-null   float64
 23  V23     1268 non-null   float64
 24  V24     1268 non-null   float64
 25  V25     1268 non-null   float64
 26  V26     1268 non-null   float64
 27  V27     1268 non-null   float64
 28  V28     1268 non-null   float64
 29  Amount  1268 non-null   float64
 30  Class   1268 non-null   int64
dtypes: float64(30), int64(1)
memory usage: 317.0 KB

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
import joblib
joblib.dump(df, 'train_prep.csv')

['train_prep.csv']

#Conclusão

Não foi necessário o imputamente de valores faltantes, pois o dataset não possui valores faltantes e foram removidos os valores duplicados